module.exports = {
    important: false,
    content: [
        "src/views/**/*.twig",
        "src/assets/js/**/*.js",
        'node_modules/@salla.sa/twilight-tailwind-theme/safe-list-css.txt',
    ],
    darkMode: 'class',
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1rem',
                sm: '1.5rem',
                lg: '2rem',
                xl: '2.5rem',
                '2xl': '3rem',
            },
            screens: {
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1536px',
            }
        },
        fontFamily: {
            sans: [
                'var(--font-main)',
                '-apple-system',
                'BlinkMacSystemFont',
                'Segoe UI',
                'Roboto',
                'Helvetica Neue',
                'Arial',
                'sans-serif',
            ],
            primary: "var(--font-main)",
            heading: "var(--font-heading, var(--font-main))"
        },
        extend: {
            colors: {
                primary: {
                    50: 'var(--color-primary-50, #f0f9ff)',
                    100: 'var(--color-primary-100, #e0f2fe)',
                    200: 'var(--color-primary-200, #bae6fd)',
                    300: 'var(--color-primary-300, #7dd3fc)',
                    400: 'var(--color-primary-400, #38bdf8)',
                    500: 'var(--color-primary, #0ea5e9)',
                    600: 'var(--color-primary-600, #0284c7)',
                    700: 'var(--color-primary-700, #0369a1)',
                    800: 'var(--color-primary-800, #075985)',
                    900: 'var(--color-primary-900, #0c4a6e)',
                    DEFAULT: 'var(--color-primary)',
                    light: 'var(--color-primary-light)',
                    dark: 'var(--color-primary-dark)',
                },
                secondary: {
                    50: 'var(--color-secondary-50, #faf5ff)',
                    100: 'var(--color-secondary-100, #f3e8ff)',
                    200: 'var(--color-secondary-200, #e9d5ff)',
                    300: 'var(--color-secondary-300, #d8b4fe)',
                    400: 'var(--color-secondary-400, #c084fc)',
                    500: 'var(--color-secondary, #a855f7)',
                    600: 'var(--color-secondary-600, #9333ea)',
                    700: 'var(--color-secondary-700, #7e22ce)',
                    800: 'var(--color-secondary-800, #6b21a8)',
                    900: 'var(--color-secondary-900, #581c87)',
                    DEFAULT: 'var(--color-secondary)',
                    light: 'var(--color-secondary-light)',
                    dark: 'var(--color-secondary-dark)',
                },
                accent: {
                    DEFAULT: 'var(--color-accent, #f59e0b)',
                    light: 'var(--color-accent-light, #fbbf24)',
                    dark: 'var(--color-accent-dark, #d97706)',
                },
                'text-main': 'var(--color-text-main, #1f2937)',
                'text-muted': 'var(--color-text-muted, #6b7280)',
                'bg-light': 'var(--color-bg-light, #f9fafb)',
                'bg-dark': 'var(--color-bg-dark, #111827)',
                success: {
                    DEFAULT: '#10B981',
                    light: '#34D399',
                    dark: '#059669',
                },
                warning: {
                    DEFAULT: '#F59E0B',
                    light: '#FBBF24',
                    dark: '#D97706',
                },
                danger: {
                    DEFAULT: '#EF4444',
                    light: '#F87171',
                    dark: '#DC2626',
                },
                info: {
                    DEFAULT: '#3B82F6',
                    light: '#60A5FA',
                    dark: '#2563EB',
                },
                dark: '#1D1F1F',
                darker: '#0E0F0F',
                light: '#F3F4F6',
                gray: {
                    50: '#F9FAFB',
                    100: '#F3F4F6',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#4B5563',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#111827',
                }
            },
            spacing: {
                '3.75': '0.9375rem',
                '4.5': '1.125rem',
                '7.5': '1.875rem',
                '15': '3.75rem',
                '18': '4.5rem',
                '22': '5.5rem',
                '26': '6.5rem',
                '30': '7.5rem',
                '50': '12.5rem',
                '58': '14.5rem',
                '62': '15.5rem',
                '74': '18.5rem',
                '76': '19rem',
                '78': '19.5rem',
                '100': '25rem',
                '116': '29rem',
                '132': '33rem',
                '200': '50rem',
            },
            borderRadius: {
                'none': '0',
                'sm': '0.125rem',
                DEFAULT: '0.5rem',
                'md': '0.75rem',
                'lg': '1rem',
                'xl': '1.25rem',
                '2xl': '1.5rem',
                '3xl': '1.875rem',
                'large': '1.375rem',
                'big': '2.5rem',
                'tiny': '0.1875rem',
                'full': '9999px',
            },
            fontSize: {
                'xxs': ['0.625rem', { lineHeight: '0.875rem' }],
                'xs': ['0.75rem', { lineHeight: '1rem' }],
                'sm': ['0.875rem', { lineHeight: '1.25rem' }],
                'base': ['1rem', { lineHeight: '1.5rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '1' }],
                '6xl': ['3.75rem', { lineHeight: '1' }],
                '7xl': ['4.5rem', { lineHeight: '1' }],
                'icon-lg': '2.0625rem',
                'title-size': '2.625rem',
            },
            boxShadow: {
                'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                'sm': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
                'default': '0 10px 30px -10px rgba(0, 0, 0, 0.1)',
                'soft': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
                'card': '0 0 20px rgba(0, 0, 0, 0.05)',
                'dropdown': '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
                'sticky': '0 -2px 10px rgba(0, 0, 0, 0.05)',
                'glow': '0 0 20px rgba(var(--color-primary-rgb), 0.3)',
                'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
            },
            zIndex: {
                '1': '1',
                '2': '2',
                '5': '5',
                '10': '10',
                '20': '20',
                '30': '30',
                '40': '40',
                '50': '50',
                'header': '90',
                'modal': '100',
                'drawer': '105',
                'tooltip': '110',
                'dropdown': '95',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeOut: {
                    '0%': { opacity: '1' },
                    '100%': { opacity: '0' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideInRight: {
                    '0%': { transform: 'translateX(100%)' },
                    '100%': { transform: 'translateX(0)' },
                },
                slideInLeft: {
                    '0%': { transform: 'translateX(-100%)' },
                    '100%': { transform: 'translateX(0)' },
                },
                slideOutRight: {
                    '0%': { transform: 'translateX(0)' },
                    '100%': { transform: 'translateX(100%)' },
                },
                slideOutLeft: {
                    '0%': { transform: 'translateX(0)' },
                    '100%': { transform: 'translateX(-100%)' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0.9)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                bounce: {
                    '0%, 100%': { transform: 'translateY(-5%)', animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)' },
                    '50%': { transform: 'translateY(0)', animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)' },
                },
                pulse: {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.5' },
                },
            },
            animation: {
                fadeIn: 'fadeIn 0.5s ease-out',
                fadeOut: 'fadeOut 0.3s ease-out',
                slideUp: 'slideUp 0.5s ease-out',
                slideDown: 'slideDown 0.3s ease-out',
                slideInRight: 'slideInRight 0.4s ease-out',
                slideInLeft: 'slideInLeft 0.4s ease-out',
                slideOutRight: 'slideOutRight 0.3s ease-out',
                slideOutLeft: 'slideOutLeft 0.3s ease-out',
                scaleIn: 'scaleIn 0.3s ease-out',
                bounce: 'bounce 1s infinite',
                pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            },
            transitionDuration: {
                '0': '0ms',
                '2000': '2000ms',
            },
            transitionTimingFunction: {
                'in-expo': 'cubic-bezier(0.95, 0.05, 0.795, 0.035)',
                'out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
            },
        },
    },
    corePlugins: {
        outline: false,
    },
    plugins: [
        require('@salla.sa/twilight-tailwind-theme'),
        require('@tailwindcss/forms'),
        require('@tailwindcss/line-clamp'),
    ],
}
